---

- name: Add PPA
  apt_repository:
    repo: "ppa:{{ item }}"
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - vbernat/haproxy-1.7

- name: Install HAProxy
  apt:
    name: haproxy
    state: latest

- name: Generate backends certificates
  include_role:
    name: pyslackers.letsencrypt
  vars:
    domains: "{{ item.value.domains }}"
    letsencrypt: "{{ item.value.letsencrypt }}"
    webserver: haproxy
  with_dict: "{{ haproxy_backends }}"
  when: item.value.letsencrypt is defined and item.value.letsencrypt

- name: Generate redirections certificates
  include_role:
    name: pyslackers.letsencrypt
  vars:
    domains: "{{ item.value.domains }}"
    letsencrypt: "{{ item.value.letsencrypt }}"
    webserver: haproxy
  with_dict: "{{ haproxy_redirects }}"
  when: item.value.letsencrypt is defined and item.value.letsencrypt

- name: Configure HAProxy
  template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: Reload HAProxy

- name: Enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes
